config:
  azure-native:location: westus3
  cst8918-a03-infra2:appPath: ../
  cst8918-a03-infra2:containerPort: '80'
  cst8918-a03-infra2:publicPort: '80'
  cst8918-a03-infra2:cpu: '1'
  cst8918-a03-infra2:memory: '2'
  cst8918-a03-infra2:prefixName: 'cst8918a03donnaha'
  cst8918-a03-infra2:imageTag: 'v0.1.0'
